[package]
name = "bevy_mod_props"
version = "1.0.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Bevy utilities for high-specificity programming."

[dependencies]
bevy_ecs = { version = "0.17.2", default-features = false }
thiserror = "2.0.17"
ustr = "1.1.0"
